### PR TITLE
[AND-2735] Expose VungleRouter to publisher for pre init sdk with HB.

### PR DESCRIPTION
**Pull request by HuFangshuai**
https://developers.mopub.com/publishers/advanced-bidding/#step-1-initialize-your-network-sdks
1. On app launch, identify where the app initializes MoPub, and preface it a couple of lines.
2. Call the corresponding initialization API from the network SDK to initialize it, and pass in any parameters or IDs as necessary.
3. Once the network finishes initializing, after a predefined wait time, initialize MoPub.

This PR expose VungleRouter#getInstance and VungleRouter#applyVungleNetworkSettings to publisher for having correct headers and VungleSettings from the start.

### CODE REVIEW

**Comment by alexander-gubov** [comment]
But if they don't pass any settings,  can be separate method better?

**Comment by HuFangshuai** [comment]
> But if they don't pass any settings, can be separate method better?

Pass null is ok, same as MoPub pass null to adapter.

**Comment by alexander-gubov** [comment]
> > But if they don't pass any settings, can be separate method better?
> 
> Pass null is ok, same as MoPub pass null to adapter.

I mean if they don't use adapter classes at all. I would propose not to expose VungleRouter, and have a static method which will only call com.mopub.mobileads.VungleRouter#getInstance to call Plugin.addWrapperInfo() inside

Could be in VungleNetworkSettings

**Comment by HuFangshuai** [comment]
> > > But if they don't pass any settings, can be separate method better?
> > 
> > 
> > Pass null is ok, same as MoPub pass null to adapter.
> 
> I mean if they don't use adapter classes at all. I would propose not to expose VungleRouter, and have a static method which will only call com.mopub.mobileads.VungleRouter#getInstance to call Plugin.addWrapperInfo() inside
> 
> Could be in VungleNetworkSettings

No, publisher must call `vungleRouter.applyVungleNetworkSettings` if no vungle network settings.
In this method adapter returned default VungleSettings and disabled banner refresh.
Not only to add HEADER_UA before init SDK.

See publisher integrate here: https://github.com/Vungle/mopub-adapter-testapp-android/pull/19/files#diff-6bf0c98f2ac50d529ae9e049f8e99374R100
```
// If no configuration, pass null.
VungleSettings vungleSettings = vungleRouter.applyVungleNetworkSettings(configuration);
```

**Review by palrahul — APPROVED** [review]
LGTM for now
Later we might need to evaluate if we can improve upon accessing VungleRouter#getInstance and VungleRouter#applyVungleNetworkSettings or should this all be under a HeaderBidding wrapper class

**Pull request merged**
