### PR TITLE
[AND-3358] Add priority placement to VungleSettings

### PR DESCRIPTION
**Pull request by alexander-gubov**
PR to use https://github.com/Vungle/vungle-android-sdk/pull/1312

### CODE REVIEW

**Review by HuFangshuai — DISMISSED** [review]
LGTM

**Comment by palrahul** [comment]
This does not belong to 6.10.1-RC , AND-3358 tagged for 6.11 so target branch should be develop

**Comment by alexander-gubov** [comment]
> This does not belong to 6.10.1-RC , AND-3358 tagged for 6.11 so target branch should be develop

develop is just too old...

**Comment by anton-blashchuk** [comment]
> > This does not belong to 6.10.1-RC , AND-3358 tagged for 6.11 so target branch should be develop
> 
> develop is just too old...

develop is fine now, but there's too much delta since I believe initial commit is based on 6.10.x-release rather than develop

**Review by jeffreychang-vungle — APPROVED** [review]

**Pull request merged**
