### PR TITLE
[AND-3884] Redesign MoPub adapter for SDK callbacks

### PR DESCRIPTION
**Pull request by HuFangshuai**
**Context**
The flow of request banner ads(based on SDK:6.11.0-early1-RC6, adapter:6.11.x-release):
image
The AdViewController in MoPub SDK has method `loadBaseAd()`, in this method has two important steps: `invalidateAdapter()` and `load()`. See https://github.com/mopub/mopub-android-sdk/blob/fe7479491db010cbdd881db35358fc1a9c901aef/mopub-sdk/mopub-sdk-base/src/main/java/com/mopub/mobileads/AdViewController.java#L790-L845

Step 1:
When requesting an ad, the `loadBaseAd()` method will be called, then will call `invalidateAdapter()`.
Step 2:
Our VungleBanner adapter instance(if exists) will be called on `onInvalidate()` method.
Step 3:
Call Vungle SDK API `destroyAd()` to destroy banner ad instance, then in AdEventListener object will call the PlayAdCallbackWrapper#onAdEnd(). 
And then, UIExecutor will post the runnable to the main UI thread message queue and wait for being called. This is the root cause let the PlayAdCallback events not be fired immediately. We can see the `onAdEnd()` event is called in step 6.
Step 4:
The flow continues to run into `load()` method, for now, MoPub creates a new VungleBanner adapter instance, and then calls the new VungleBanner adapter instance to load the banner ad. 
Step 5:
The new banner adapter will call `Banners.loadAd()->AdLoader.load(op)`. In `AdLoader.load()` the loading stuff will be run in backgroundExector, and then the main flow will return back. When the current flow is completed, the next message will be run, this's step 6.
Step 6:
The `onAdEnd()` event will be run in this step while the previous UI thread message is completed. So we can see the `onAdEnd()` is called in the old VungleBanner adapter instance.
**The root cause** is in step 6, we called `VungleRouter#removeRouterListener()` in the onAdEnd() callback, this makes the 
new VungleRouterListener instance(generated in the new VungleBanner instance) got removed. So the loaded callback can not be fired to the target listener.

**About bugfix**
1. Redesign the load&play callbacks in VungleRouter class, remove from it and implement them in each adapter instance.
2. Meanwhile redesign the SDK initialize process in MoPub adapter.
3. No need to create the bridge load&play callbacks in VungleRouter class:
image

### CODE REVIEW

**Comment by palrahul** [comment]
@HuFangshuai will be great to add some info on PR desc so we can get some context into why this change is required,
what changed from 6.10.x

**Comment by HuFangshuai** [comment]
> @HuFangshuai will be great to add some info on PR desc so we can get some context into why this change is required, what changed from 6.10.x

Yes, updated.

**Comment by felixzhang0703** [comment]
Since this is a huge change for mopub adapter, Fangshuai has another PR(workaround solution) to fix this issue. https://github.com/Vungle/vungle-android-sdk/pull/1525/files  (Check if main thread, call playAdCallback.onAdEnd immediately instead of using uiexecutor.execute())
Please help to consider which approach we should use.
cc @palrahul @anton-blashchuk-zoolatech @jiancchen @jeffreychang-vungle

**Comment by jeffreychang-vungle** [comment]
Good documentation thanks @HuFangshuai

**Comment by jeffreychang-vungle** [comment]
Had been able to reproduce and test this solution. Works as expected and the code looks solid

**Comment by anton-blashchuk** [comment]
is the plan to replace the other(more temporary) solution with this one?

**Comment by HuFangshuai** [comment]
sunset mopub adapter.

**Pull request closed without merging**
